# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

ci:
    autoupdate_schedule: monthly

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: end-of-file-fixer
    - id: check-json
    - id: check-toml
    - id: check-shebang-scripts-are-executable
    - id: mixed-line-ending
    - id: check-docstring-first
    - id: debug-statements
    - id: check-yaml
      args: ["--unsafe"]
    - id: check-added-large-files
      args: ["--maxkb=750"]
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black-jupyter
    - id: black
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ["-c", 'pyproject.toml']
        additional_dependencies: ["bandit[toml]"]
- repo: https://github.com/hadialqattan/pycln
  rev: v2.4.0 # Possible releases: https://github.com/hadialqattan/pycln/releases
  hooks:
    - id: pycln
      args: [--config=pyproject.toml]
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black"]
    - id: isort
      name: isort (cython)
      types: [cython]
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
      additional_dependencies: [
        flake8-bugbear==22.7.1,
        flake8-logging-format==0.7.4,
        flake8-2020==1.6.1,
      ]
