#======================================================================================================================#
#                                            pyXs Configuration File                                                   #
#                                     +--------------------------------------+                                         #
#                                                                                                                      #
# This file contains the basic configuration settings for pyXs. See the line comments for details on                   #
#   specific settings. Users are encouraged to edit settings and / or change settings as necessary.                    #
#                                                                                                                      #
# --- These settings are accessed using the xsparams variable    ------------------------------------------------------#
#======================================================================================================================#
system:
  # -- These are system-wide settings for basic usage. -- #
  logging:
    main:
      enabled: true # Use this to disable any logging. This will stop output to terminal!
      format: "%(name)-3s : [%(levelname)-9s] %(asctime)s %(message)s" # Logger's string format for output
      level: "DEBUG" # Only logging passed to this level or higher are displayed.
      stream: "STDERR" # Can be STDERR or STDOUT.
    developer:
      # ! The developer logger passes detailed logging messages to file
      enabled: false
      output_directory: null # You have to set this before the development logger will function.
  add_ons:
    rich: false

#======================================================================================================================#
plotting:
  # These are options for any of the default plots generated in cluster generator.
  defaults:
    # -- Latex settings -- #
    text.usetex: true
    # -- Tick Settings -- #
    xtick.major.size: 8
    ytick.major.size: 8
    xtick.minor.size: 5
    ytick.minor.size: 5
    xtick.top: true
    xtick.bottom: true
    xtick.labeltop: false
    xtick.labelbottom: true
    xtick.minor.visible: true
    ytick.left: true
    ytick.right: true
    ytick.labelleft: true
    ytick.labelright: false
    ytick.minor.visible: true
    xtick.direction: "in"
    ytick.direction: "in"
    # -- Font Settings -- #
    font.style: "normal"
    font.size: 12
    # -- Image -- #
    image.cmap: 'inferno'
